### ISSUE TITLE
Location Freezing

### ISSUE THREAD

**Issue by NiffirgkcaJ** [amit9838/mousam#154]
Hi! I would like to say that the application is beautiful, but it is incredibly slow at fetching update data and is freezing when I try to add a location!

**Comment by amit9838** [comment]
Hi @NiffirgkcaJ  can you try uninstalling the app completely and reinstalling it again. Hopefully this should solve the issue.
would be nice if you share your system info.

**Comment by NiffirgkcaJ** [comment]
I apologize for the late response, but I already tried reinstalling it and it's still the same. The main crux of the issue is when I try to search for a new location to add, it freezes for a while before showing the list of locations in that area.

Screenshot example:
![image](https://github.com/user-attachments/assets/90003154-d4ed-4aa8-a0e6-68a834b979ee)

As for my system info, I have this [link](https://linux-hardware.org/?probe=0ca4e52c33) and this screenshot.
![image](https://github.com/user-attachments/assets/e616d4ac-f5cb-4e4a-afd2-00a674423995)

**Comment by amit9838** [comment]
Are you facing a similar issue with any other app?
Looks like this gnome-runtime is the issue for this behaviour.

**Comment by NiffirgkcaJ** [comment]
> Are you facing a similar issue with any other app? Looks like this gnome-runtime is the issue for this behaviour.

Nope! I'm not having this issue with any applications, though, I can say that I'm having issues with Steam when adding a non-Steam game, but it's not consistent like this one.
